name: Test (vitest & playwright - macOS)

concurrency:
  group: macos-test-${{ github.head_ref }}
  cancel-in-progress: true

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [main]

  merge_group:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ut-mac:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [22.x]
        os: [macos-14] # M1 Mac

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 1

      - name: Install Pnpm
        run: |
          npm install -g corepack@latest --force
          corepack enable

      - name: Check skip CI
        run: echo "RESULT=$(node ./scripts/skipCI.js)" >> "$GITHUB_OUTPUT"
        id: skip-ci

      - name: Log skip CI result
        run: echo "${{steps.skip-ci.outputs.RESULT}}"

      - name: Setup Node.js ${{ matrix.node-version }}
        if: ${{steps.skip-ci.outputs.RESULT != 'true'}}
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Nx Cache
        id: nx-cache
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: nx-${{ github.ref_name }}-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            nx-${{ github.ref_name }}-${{ runner.os }}

      - name: Install Dependencies
        if: ${{steps.skip-ci.outputs.RESULT != 'true'}}
        run: pnpm install --ignore-scripts

      - name: Build Packages
        if: ${{steps.skip-ci.outputs.RESULT != 'true'}}
        run: pnpm run build

      - name: Build Website # for test
        if: ${{steps.skip-ci.outputs.RESULT != 'true'}}
        run: pnpm run build:website

      - name: Unit Test
        if: ${{steps.skip-ci.outputs.RESULT != 'true'}}
        run: pnpm run test:unit

      - name: E2E Test
        if: ${{steps.skip-ci.outputs.RESULT != 'true'}}
        run: pnpm playwright install --with-deps chromium && pnpm run test:e2e

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14
